### PR TITLE
bug fixed

### PR DESCRIPTION
**Pull request by praweensoni01**

### CODE REVIEW

**Comment by andmhn** [comment]
intro ke color ko change nhi karo

**Comment by praweensoni01** [comment]
Nhi kiye hai

**Comment by andmhn** [comment]
#welcome id ka color white accha hoga

**Comment by andmhn** [comment]
aur box ka corner round kar do

**Comment by praweensoni01** [comment]
Kon sa box

**Comment by praweensoni01** [comment]
#welcome wala

**Comment by andmhn** [comment]
ha

**Comment by andmhn** [comment]
#welcome{
    font-size: 50px;
    color: #C3FA95;
    box-shadow: 0px 0px 30px rgba(227, 228, 237, 0.37);
    backdrop-filter: blur(10px);
    border: 1.5px solid rgba(255, 255, 255, 0.18);
    border-radius: 5px;
    margin: 5px 30px;
    font-size:60px;
    padding: 15px;
    font-family: Georgia, 'Times New Roman', Times, serif;
}

**Comment by praweensoni01** [comment]
Round to kiye hai 5px dekho

**Pull request merged**
